language: objective-c

xcode_project: Solar.xcodeproj
xcode_scheme: SolarTests
xcode_sdk: iphonesimulator9.3
osx_image: xcode8

script:
- xcodebuild clean build test -project Solar.xcodeproj -scheme Solar -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3'